### ISSUE TITLE
FileNotFoundError, issue running demo on Google Colab 

### ISSUE THREAD

**Issue by dptru10** [nanotheorygroup/kaldo#59]
Hello! 

I'm having issues executing a kaldo/lammps demo on Google Colab (https://colab.research.google.com/drive/1kmuLpEJ0Gqj6RULd2w7o7pEagz5_aK27?usp=sharing), any ideas? 

```
2022-10-28 18:10:53,088 - kaldo - INFO - Second order not found. Calculating.
INFO:kaldo:Second order not found. Calculating.
2022-10-28 18:10:53,096 - kaldo - INFO - Calculating second order potential derivatives, finite difference displacement: 1.000e-04 angstrom
INFO:kaldo:Calculating second order potential derivatives, finite difference displacement: 1.000e-04 angstrom
Exception ignored in: <function lammps.__del__ at 0x7f0268a990e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lammps.py", line 225, in __del__
    if self.lmp and self.opened:
AttributeError: 'lammps' object has no attribute 'lmp'
Exception ignored in: <function lammps.__del__ at 0x7f0268a990e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lammps.py", line 225, in __del__
    if self.lmp and self.opened:
AttributeError: 'lammps' object has no attribute 'lmp'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/kaldo/observables/secondorder.py](https://7mwtagy0w39-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221026-060043-RC00_483928510#) in calculate(self, calculator, delta_shift, is_storing, is_verbose)
    219                 self.value = SecondOrder.load(folder=self.folder, supercell=self.supercell, format='numpy',
--> 220                                                 is_acoustic_sum=self.is_acoustic_sum).value
    221 

19 frames
FileNotFoundError: [Errno 2] No such file or directory: 'displacement/replicated_atoms.xyz'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/lib/python3.7/ctypes/__init__.py](https://7mwtagy0w39-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221026-060043-RC00_483928510#) in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: liblammps.so: cannot open shared object file: No such file or directory
```

**Comment by ZKC19940412** [comment]
Hi.  Judging from the error messages, It looks like a lammps.so symlink/cuda toolkit version issue and we are actively coming up with a fix for it. In the meantime, I suggest, if possible, installing kALDo in your local machine and try the example calculations in the following folder: https://github.com/nanotheorygroup/kaldo/tree/main/examples.

We should contact you once the fix for the colab examples is done. Again, thanks for point it out. Please let us know if you have further questions.

Best, 
Zekun

**Comment by ZKC19940412** [comment]
Here is a fixed version for the bulk silicon colab demo (bare with me making it as a  zip file as that is the few type of files github will allow for uploading): 
[crystal_presentation_2022_Oct_28th.zip](https://github.com/nanotheorygroup/kaldo/files/9893044/crystal_presentation_2022_Oct_28th.zip) and we will make it public after cleaning up the amorphous silicon examples. Again please let me know if you have another questions and thanks for trying out kALDO.

Best, 
Zekun

**Comment by ZKC19940412** [comment]
Fixes for both colab demo are in place in the official repo now. Thank you so much for pointing it out.

Best, 
Zekun

**Comment by dptru10** [comment]
Thanks for your fixes, greatly appreciated!
