### ISSUE TITLE
Invalid value when calculating velocity

### ISSUE THREAD

**Issue by mu-dian** [nanotheorygroup/kaldo#91]
Dear developers,

I try to calculate the thermal conductivity by solving BTE through rta method. My commands are as follows: 

```
print('RTA method \n')
rta_cond = Conductivity(phonons=phonons, method='rta', storage='formatted')
rta_cond.diffusivity_bandwidth = phonons.bandwidth
print('Conductivity from RTA (W/m-K): %.3f' % (np.mean(np.diag(rta_cond.conductivity.sum(axis=0)))))
print(rta_cond.conductivity.sum(axis=0))
```

It can calculate third order projection successfully, but it then comes out an error as follows:

```
2023-07-10 17:58:35,973 - kaldo - INFO - ALD_alpha/2_2_2/velocity not found in formatted format, calculating velocity
/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/observables/harmonic_with_q.py:209: RuntimeWarning: invalid value encountered in sqrt
  inverse_sqrt_freq = tf.cast(tf.convert_to_tensor(1 / np.sqrt(frequency)), tf.complex128)
Traceback (most recent call last):
  File "kaldo_DOS_test.py", line 67, in <module>
    print('Conductivity from RTA (W/m-K): %.3f' % (np.mean(np.diag(rta_cond.conductivity.sum(axis=0)))))
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 207, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/conductivity.py", line 167, in conductivity
    lambd = self.mean_free_path
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 207, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/conductivity.py", line 201, in mean_free_path
    cond = self._calculate_mfp_sc()
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/conductivity.py", line 510, in _calculate_mfp_sc
    velocity = phonons.velocity.real.reshape ((phonons.n_k_points, phonons.n_modes, 3))
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 207, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/phonons.py", line 180, in velocity
    velocity[ik] = phonon.velocity
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 214, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/observables/harmonic_with_q.py", line 52, in velocity
    velocity = self.calculate_velocity()
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/observables/harmonic_with_q.py", line 217, in calculate_velocity
    velocity_AF = 1 / (2 * np.pi) * contract('mn,m,n->mn', sij,
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/contract.py", line 507, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/contract.py", line 591, in _core_contract
    new_view = _einsum(einsum_str, *tmp_operands, backend=backend, **einsum_kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/sharing.py", line 151, in cached_einsum
    return einsum(*args, **kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/contract.py", line 353, in _einsum
    return fn(einsum_str, *operands, **kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Einsum as input #1(zero-based) was expected to be a complex128 tensor but is a double tensor [Op:Einsum]

```
I can not find out the reason. So I seek for your help. 
Thanks in advance.

**Comment by mu-dian** [comment]
I try to add `frequency_v1 = tf.cast(frequency,dtype=tf.complex128)` into harmonic_with_q.py. Now, no more invalid value encountered in sqrt. 
However, the traceback error still exists: 
`Traceback (most recent call last):
  File "kaldo_DOS_test.py", line 67, in <module>
    print('Conductivity from RTA (W/m-K): %.3f' % (np.mean(np.diag(rta_cond.conductivity.sum(axis=0)))))
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 207, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/conductivity.py", line 167, in conductivity
    lambd = self.mean_free_path
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 207, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/conductivity.py", line 201, in mean_free_path
    cond = self._calculate_mfp_sc()
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/conductivity.py", line 510, in _calculate_mfp_sc
    velocity = phonons.velocity.real.reshape ((phonons.n_k_points, phonons.n_modes, 3))
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 207, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/phonons.py", line 180, in velocity
    velocity[ik] = phonon.velocity
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/helpers/storage.py", line 214, in __lazy_property
    loaded_attr = fn(self)
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/observables/harmonic_with_q.py", line 52, in velocity
    velocity = self.calculate_velocity()
  File "/home/liushiLab/zhouwenjie/software/kaldo_lammps/kaldo/kaldo/observables/harmonic_with_q.py", line 219, in calculate_velocity
    velocity_AF = 1 / (2 * np.pi) * contract('mn,m,n->mn', sij,
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/contract.py", line 507, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/contract.py", line 591, in _core_contract
    new_view = _einsum(einsum_str, *tmp_operands, backend=backend, **einsum_kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/sharing.py", line 151, in cached_einsum
    return einsum(*args, **kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/opt_einsum/contract.py", line 353, in _einsum
    return fn(einsum_str, *operands, **kwargs)
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/liushiLab/zhouwenjie/.conda/envs/kaldo2/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Einsum as input #1(zero-based) was expected to be a complex128 tensor but is a double tensor [Op:Einsum]
`

**Comment by ZKC19940412** [comment]
Hi, mu-dian. This is Zekun. It looks like a tensorflow/numpy version issue from the first glance. However, without looking into more files it is a bit difficult to point out what actually went wrong.  

Here is my emai:zkuchen@ucdavis.edu, please feel free to reach out. 

Best, 
Zekun

**Comment by niklundgren** [comment]
Ya, it’d be helpful to see more of the input script and possibly the data too so we can recreate it.

We use floats for amorphous systems (that are always calculated at Gamma) and crystals at gamma. 

Would it be tractable to get us the inputs? Or at least the full input script, and you can tell me a little more about the data you’re using?
My first hunch is that it’s probably

**Comment by ZKC19940412** [comment]
I believe this issue is handled and solved. Feel free to close it. @niklundgren
